# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
        #          1
        #  1 + 1 = 2
        #  2 + 1 = 3
        #  3 + 2 = 5
        #  5 + 3 = 8

n = 4000000

x = 0
first = 1
second = 1
fib = 1
next = 1
while next <= n:
    if next%2 == 0:
        x += next
    next = first + second
    first = second
    second = next

print(x)